GET http://localhost:3001/api/persons



###
GET http://localhost:3001/api/persons/invalidID



###
GET http://localhost:3001/info



###
DELETE  http://localhost:3001/api/persons/63df7df3ac4f35ba4ad7bf67



###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Azeez",
    "number": "0817-977-6940"
}